In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#reading the datasets
df1 = pd.read_csv('MSCI_Data.csv')
df2 = pd.read_csv('All_Equities_Dataset.csv')

In [3]:
df1.head()

,Date,MSCI USA,MSCI USA Value,MSCI USA Low Size,MSCI USA Low Volatility,MSCI USA High Dividend Yield,MSCI USA Quality,MSCI USA Momentum
0,1/29/1999,2673.05,3277.734545,2384.21,995.479542,997.649417,683.831934,512.942863
1,2/26/1999,2598.02,3251.106568,2391.18,969.079546,970.419053,658.588413,500.178311
2,3/31/1999,2705.67,3332.419537,2344.66,989.782505,967.408227,682.563547,528.966699
3,4/30/1999,2802.00,3624.972158,2410.24,1033.753199,1064.030284,688.421002,530.437255
4,5/31/1999,2736.32,3560.597835,2663.08,1024.310711,1045.278656,672.911109,515.715429

In [5]:
df1 = df1.set_index('Date')

In [8]:
df2 = df2.set_index('Dates')

In [7]:
df2.head()

,Dates,KATE US Equity,KBH US Equity,KDP US Equity,KEY US Equity,KEYS US Equity,KHC UW Equity,KIM US Equity,KLAC UQ Equity,KLAC UW Equity,...,CTSH UW Equity,CTVA US Equity,CTXS UQ Equity,CTXS UW Equity,CVC US Equity,CVG US Equity,CVH US Equity,CVS US Equity,CVX US Equity,CXO US Equity
0,1/29/1993,19.8750,8.6875,NaN,16.0625,NaN,NaN,7.3056,3.125,3.125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2/26/1993,17.1875,9.3125,NaN,16.1875,NaN,NaN,7.2778,3.219,3.219,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3/31/1993,18.3750,9.0000,NaN,17.3125,NaN,NaN,7.5833,3.563,3.563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/30/1993,17.5000,8.3750,NaN,16.2500,NaN,NaN,7.4444,3.063,3.063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5/31/1993,16.8125,8.7500,NaN,15.5000,NaN,NaN,6.8889,4.500,4.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
merged_df = pd.merge(df1, df2, left_index = True, right_index = True, how='inner')
print(merged_df.head())

           MSCI USA  MSCI USA Value  MSCI USA Low Size  \
1/29/1999   2673.05     3277.734545            2384.21
2/26/1999   2598.02     3251.106568            2391.18
3/31/1999   2705.67     3332.419537            2344.66
4/30/1999   2802.00     3624.972158            2410.24
5/31/1999   2736.32     3560.597835            2663.08

           MSCI USA Low Volatility  MSCI USA High Dividend Yield  \
1/29/1999               995.479542                    997.649417
2/26/1999               969.079546                    970.419053
3/31/1999               989.782505                    967.408227
4/30/1999              1033.753199                   1064.030284
5/31/1999              1024.310711                   1045.278656

           MSCI USA Quality  MSCI USA Momentum  KATE US Equity  KBH US Equity  \
1/29/1999        683.831934         512.942863         19.0938        14.0938
2/26/1999        658.588413         500.178311         16.8438        11.2500
3/31/1999        682.563547         528.966699         16.3125        11.2813
4/30/1999        688.421002         530.437255         16.5313        12.1563
5/31/1999        672.911109         515.715429         18.0000        12.0625

           KDP US Equity  ...  CTSH UW Equity  CTVA US Equity  CTXS UQ Equity  \
1/29/1999            NaN  ...          0.8099             NaN         18.0409
2/26/1999            NaN  ...          0.8958             NaN         15.3534
3/31/1999            NaN  ...          0.5781             NaN         15.1793
4/30/1999            NaN  ...          0.4674             NaN         16.9211
5/31/1999            NaN  ...          0.5234             NaN         19.6833

           CTXS UW Equity  CVC US Equity  CVG US Equity  CVH US Equity  \
1/29/1999         18.0409        33.0573        18.0000         4.3333
2/26/1999         15.3534        31.8920        17.3125         4.7639
3/31/1999         15.1793        36.3692        17.1250         3.3333
4/30/1999         16.9211        37.9638        18.5625         4.0833
5/31/1999         19.6833        38.6997        17.6250         5.8889

           CVS US Equity  CVX US Equity  CXO US Equity
1/29/1999        27.3750        37.2500            NaN
2/26/1999        26.5000        38.4375            NaN
3/31/1999        23.7500        44.3750            NaN
4/30/1999        23.8125        49.8750            NaN
5/31/1999        23.0000        46.2500            NaN

[5 rows x 1159 columns]

In [10]:
#Calculating the Returns
returns_data = merged_df.pct_change()

/var/folders/gg/gk_rsfjs0ll0wmb2524tp5_h0000gn/T/ipykernel_28830/388607537.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns_data = merged_df.pct_change()

In [11]:
returns_data.head()

,MSCI USA,MSCI USA Value,MSCI USA Low Size,MSCI USA Low Volatility,MSCI USA High Dividend Yield,MSCI USA Quality,MSCI USA Momentum,KATE US Equity,KBH US Equity,KDP US Equity,...,CTSH UW Equity,CTVA US Equity,CTXS UQ Equity,CTXS UW Equity,CVC US Equity,CVG US Equity,CVH US Equity,CVS US Equity,CVX US Equity,CXO US Equity
1/29/1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2/26/1999,-0.028069,-0.008124,0.002923,-0.026520,-0.027295,-0.036915,-0.024885,-0.117839,-0.201777,NaN,...,0.106062,NaN,-0.148967,-0.148967,-0.035251,-0.038194,0.099370,-0.031963,0.031879,NaN
3/31/1999,0.041435,0.025011,-0.019455,0.021364,-0.003103,0.036404,0.057556,-0.031543,0.002782,NaN,...,-0.354655,NaN,-0.011340,-0.011340,0.140386,-0.010830,-0.300300,-0.103774,0.154472,NaN
4/30/1999,0.035603,0.087790,0.027970,0.044425,0.099877,0.008582,0.002780,0.013413,0.077562,NaN,...,-0.191489,NaN,0.114748,0.114748,0.043845,0.083942,0.225002,0.002632,0.123944,NaN
5/31/1999,-0.023440,-0.017759,0.104902,-0.009134,-0.017623,-0.022530,-0.027754,0.088844,-0.007716,NaN,...,0.119812,NaN,0.163240,0.163240,0.019384,-0.050505,0.442191,-0.034121,-0.072682,NaN

In [12]:
#Beta Calculation
#Defining our targets
targets = ['MSCI USA', 'MSCI USA Value', 'MSCI USA Low Volatility', 'MSCI USA Low Size',
           'MSCI USA High Dividend Yield', 'MSCI USA Quality', 'MSCI USA Momentum']

In [15]:
#Defining Equities
equities = [col for col in returns_data.columns if col not in targets ]
equities

['KATE US Equity',
 'KBH US Equity',
 'KDP US Equity',
 'KEY US Equity',
 'KEYS US Equity',
 'KHC UW Equity',
 'KIM US Equity',
 'KLAC UQ Equity',
 'KLAC UW Equity',
 'KMB US Equity',
 'KMI US Equity',
 'KMRTQ US Equity',
 'KMX US Equity',
 'KO US Equity',
 'KR US Equity',
 'KRB US Equity',
 'KRFT UW Equity',
 'KRI US Equity',
 'KSE US Equity',
 'KSS US Equity',
 'KSU US Equity',
 'L US Equity',
 'LDG US Equity',
 'LDOS US Equity',
 'LDWIF US Equity',
 'LEG US Equity',
 'LEHMQ US Equity',
 'LEN US Equity',
 'LHX US Equity',
 'LIN US Equity',
 'LKQ UW Equity',
 'LLTC UQ Equity',
 'LLTC UW Equity',
 'LLY US Equity',
 'LM US Equity',
 'LMT US Equity',
 'LNC US Equity',
 'LNT US Equity',
 'LNT UW Equity',
 'LO US Equity',
 'LOW US Equity',
 'LPX US Equity',
 'LRCX UW Equity',
 'LUMN US Equity',
 'LUV US Equity',
 'LVLT US Equity',
 'LVS US Equity',
 'LW US Equity',
 'LXK US Equity',
 'LYB US Equity',
 'M US Equity',
 'MA US Equity',
 'MAA US Equity',
 'MAC US Equity',
 'MAR US Equity',
 'MAR UW Equity',
 'MAS US Equity',
 'MAT US Equity',
 'MAT UW Equity',
 'MBI US Equity',
 'MCD US Equity',
 'MCHP UW Equity',
 'MCK US Equity',
 'MCO US Equity',
 'MDLZ US Equity',
 'MDLZ UW Equity',
 'MDP US Equity',
 'MDRIQ US Equity',
 'MDT US Equity',
 'MEE US Equity',
 'MEL US Equity',
 'MER US Equity',
 'MET US Equity',
 'META UW Equity',
 'MFE US Equity',
 'MGM US Equity',
 'MHK US Equity',
 'MHS US Equity',
 'MIRKQ US Equity',
 'MJN US Equity',
 'MKC US Equity',
 'MKG US Equity',
 'MKTX UW Equity',
 'MLM US Equity',
 'MMM US Equity',
 'MNKKQ US Equity',
 'MNST UW Equity',
 'MO US Equity',
 'MOLX UQ Equity',
 'MOLX UW Equity',
 'MOS US Equity',
 'MPC US Equity',
 'MRK US Equity',
 'MRO US Equity',
 'MRSH US Equity',
 'MS US Equity',
 'MSCI US Equity',
 'MSFT UQ Equity',
 'MSFT UW Equity',
 'MSI US Equity',
 'MTB US Equity',
 'MTD US Equity',
 'MTG US Equity',
 'MTLQQ US Equity',
 'MTW US Equity',
 'MU US Equity',
 'MU UW Equity',
 'MUR US Equity',
 'MWI US Equity',
 'MWV US Equity',
 'MWW US Equity',
 'MWW UQ Equity',
 'MWW UW Equity',
 'MXIM UQ Equity',
 'MXIM UW Equity',
 'MYL US Equity',
 'MYL UW Equity',
 'MZIAQ US Equity',
 'NAV US Equity',
 'NAVI UW Equity',
 'NBL US Equity',
 'NBR US Equity',
 'NBR UA Equity',
 'NC US Equity',
 'NCC US Equity',
 'NCE US Equity',
 'NCLH US Equity',
 'NDAQ UW Equity',
 'NEBLQ US Equity',
 'NEE US Equity',
 'NEM US Equity',
 'NFB US Equity',
 'NFLX UW Equity',
 'NFX US Equity',
 'NGH US Equity',
 'NI US Equity',
 'NKE US Equity',
 'NKTR UW Equity',
 'NLSN US Equity',
 'NMK US Equity',
 'NOC US Equity',
 'NOV US Equity',
 'NOVL UQ Equity',
 'NOVL UW Equity',
 'NRG US Equity',
 'NRTLQ US Equity',
 'NSC US Equity',
 'NTAP UQ Equity',
 'NTAP UW Equity',
 'NTRS UQ Equity',
 'NTRS UW Equity',
 'NUE US Equity',
 'NVDA UQ Equity',
 'NVDA UW Equity',
 'NVR US Equity',
 'NWL US Equity',
 'NWL UW Equity',
 'NWS UW Equity',
 'NWSA UW Equity',
 'NXTL UQ Equity',
 'NYT US Equity',
 'O US Equity',
 'OAT US Equity',
 'OI US Equity',
 'OK US Equity',
 'OKE US Equity',
 'OMC US Equity',
 'OMX US Equity',
 'ORCL US Equity',
 'ORCL UQ Equity',
 'ORCL UW Equity',
 'ORLY UW Equity',
 'ORX US Equity',
 'OWENQ US Equity',
 'OXY US Equity',
 'PALM UQ Equity',
 'PARA US Equity',
 'PARA UA Equity',
 'PAYX UQ Equity',
 'PAYX UW Equity',
 'PBCT UW Equity',
 'PBG US Equity',
 'PBI US Equity',
 'PCAR UQ Equity',
 'PCAR UW Equity',
 'PCG US Equity',
 'PCH US Equity',
 'PCP US Equity',
 'PDCO UQ Equity',
 'PDCO UW Equity',
 'PDG US Equity',
 'PEG US Equity',
 'PEP US Equity',
 'PEP UW Equity',
 'PETM UW Equity',
 'PFE US Equity',
 'PFG US Equity',
 'PFG UW Equity',
 'PG US Equity',
 'PGL US Equity',
 'PGR US Equity',
 'PH US Equity',
 'PHM US Equity',
 'PKG US Equity',
 'PLD US Equity',
 'PM US Equity',
 'PMCS UQ Equity',
 'PMCS UW Equity',
 'PNC US Equity',
 'PNR US Equity',
 'PNW US Equity',
 'PPG US Equity',
 'PPL US Equity',
 'PPW US Equity',
 'PRDCQ US Equity',
 'PRGO US Equity',
 'PRGO UW Equity',
 'PRU US Equity',
 'PSA US Equity',
 'PSX US Equity',
 'PTC UQ Equity',
 'PTC UW Equity',
 'PTV US Equity',
 'PVH US Equity',
 'PVN US Equity',
 'PWR US Equity',
 'PXD US Equity',
 'PYPL UW Equity',
 'QCOM UQ Equity',
 'QCOM UW Equity',
 'QEP US Equity',
 'QLGC UQ Equity',
 'QLGC UW Equity',
 'QRVO UW Equity',
 'QTRN UQ Equity',
 'R US Equity',
 'RADCQ US Equity',
 'RAI US Equity',
 'RATL UQ Equity',
 'RBD US Equity',
 'RBK US Equity',
 'RCL US Equity',
 'RDC US Equity',
 'RDPL US Equity',
 'REG US Equity',
 'REG UW Equity',
 'REGN UW Equity',
 'RF US Equity',
 'RHI US Equity',
 'RHT US Equity',
 'RIG US Equity',
 'RJF US Equity',
 'RL US Equity',
 'RMD US Equity',
 'RML US Equity',
 'RNB US Equity',
 'ROH US Equity',
 'ROK US Equity',
 'ROL US Equity',
 'ROP US Equity',
 'ROST UW Equity',
 'RRC US Equity',
 'RRD US Equity',
 'RRD UW Equity',
 'RSG US Equity',
 'RSHCQ US Equity',
 'RTN US Equity',
 'RTX US Equity',
 'RVTY US Equity',
 'RX US Equity',
 'RYC US Equity',
 'SANM UQ Equity',
 'SANM UW Equity',
 'SAPE UQ Equity',
 'SBAC UW Equity',
 'SBUX UQ Equity',
 'SBUX UW Equity',
 'SCG US Equity',
 'SCHW US Equity',
 'SCHW UQ Equity',
 'SCHW UW Equity',
 'SCI US Equity',
 'SEBL UQ Equity',
 'SEE US Equity',
 'SGID US Equity',
 'SHLDQ UQ Equity',
 'SHLDQ UW Equity',
 'SHW US Equity',
 'SIAL UQ Equity',
 'SIAL UW Equity',
 'SIG US Equity',
 'SITC US Equity',
 'SIVBQ UW Equity',
 'SJM US Equity',
 'SLB US Equity',
 'SLG US Equity',
 'SLM US Equity',
 'SLM UW Equity',
 'SNA US Equity',
 'SNPS UW Equity',
 'SNV US Equity',
 'SO US Equity',
 'SOV US Equity',
 'SPG US Equity',
 'SPGI US Equity',
 'SRCL UW Equity',
 'SRE US Equity',
 'SSP US Equity',
 'STJ US Equity',
 'STT US Equity',
 'STX UW Equity',
 'STZ US Equity',
 'SUNEQ US Equity',
 'SVU US Equity',
 'SWK US Equity',
 'SWKS UW Equity',
 'SWN US Equity',
 'SWY US Equity',
 'SXCL UQ Equity',
 'SYF US Equity',
 'SYK US Equity',
 'SYY US Equity',
 'T US Equity',
 'TAP US Equity',
 'TAP UQ Equity',
 'TAP/B US Equity',
 'TCOMA UQ Equity',
 'TDC US Equity',
 'TDG US Equity',
 'TEG US Equity',
 'TER US Equity',
 'TEX US Equity',
 'TFC US Equity',
 'TFCF UW Equity',
 'TFCFA US Equity',
 'TFCFA UW Equity',
 'TFX US Equity',
 'TGNA US Equity',
 'TGT US Equity',
 'THC US Equity',
 'TIE US Equity',
 'TIN US Equity',
 'TJX US Equity',
 'TKR US Equity',
 'TLAB UQ Equity',
 'TLAB UW Equity',
 'TMO US Equity',
 'TMUS US Equity',
 'TMUS UW Equity',
 'TNB US Equity',
 'TNL US Equity',
 'TOY US Equity',
 'TPR US Equity',
 'TRB US Equity',
 'TRIP UW Equity',
 'TROW UQ Equity',
 'TROW UW Equity',
 'TRV US Equity',
 'TSCO UW Equity',
 'TSN US Equity',
 'TSS US Equity',
 'TT US Equity',
 'TTWO UW Equity',
 'TUPBQ US Equity',
 'TWC US Equity',
 'TWTR US Equity',
 'TWX US Equity',
 'TXN US Equity',
 'TXN UW Equity',
 'TXT US Equity',
 'TXU US Equity',
 'UA US Equity',
 'UAA US Equity',
 'UAL US Equity',
 'UAL UW Equity',
 'UAWGQ US Equity',
 'UCM US Equity',
 'UDR US Equity',
 'UHS US Equity',
 'UIS US Equity',
 'ULTA UW Equity',
 'UMGI US Equity',
 'UN US Equity',
 'UNH US Equity',
 'UNM US Equity',
 'UNP US Equity',
 'UPS US Equity',
 'URBN UW Equity',
 'URI US Equity',
 'USB US Equity',
 'USW US Equity',
 'V US Equity',
 'VALPQ US Equity',
 'VAR US Equity',
 'VFC US Equity',
 'VIAB US Equity',
 'VIAB UW Equity',
 'VIAV UQ Equity',
 'VIAV UW Equity',
 'VLO US Equity',
 'VMC US Equity',
 'VNO US Equity',
 'VRSK UW Equity',
 'VRSN UQ Equity',
 'VRSN UW Equity',
 'VRTX UW Equity',
 'VSTNQ US Equity',
 'VTR US Equity',
 'VTSS UQ Equity',
 'VYX US Equity',
 'VZ US Equity',
 'WAB US Equity',
 'WAMUQ US Equity',
 'WAT US Equity',
 'WBA US Equity',
 'WBA UW Equity',
 'WCG US Equity',
 'WCOEQ UQ Equity',
 'WDC US Equity',
 'WDC UW Equity',
 'WEC US Equity',
 'WELL US Equity',
 'WFC US Equity',
 'WFM UQ Equity',
 'WFM UW Equity',
 'WFTIQ US Equity',
 'WHR US Equity',
 'WINMQ US Equity',
 'WINMQ UW Equity',
 'WLA US Equity',
 'WM US Equity',
 'WMB US Equity',
 'WMT US Equity',
 'WNDXQ US Equity',
 'WOR US Equity',
 'WOR UQ Equity',
 'WPX US Equity',
 'WRK US Equity',
 'WTW UW Equity',
 'WU US Equity',
 'WWY US Equity',
 'WY US Equity',
 'WYE US Equity',
 'WYNN UW Equity',
 'X US Equity',
 'XEC US Equity',
 'XEL US Equity',
 'XEL UW Equity',
 'XLNX UQ Equity',
 'XLNX UW Equity',
 'XOM US Equity',
 'XRAY UW Equity',
 'XRX US Equity',
 'XTO US Equity',
 'XYL US Equity',
 'XYL UN Equity',
 'YNR US Equity',
 'YUM US Equity',
 'YUM UN Equity',
 'ZBH US Equity',
 'ZBH UN Equity',
 'ZION UQ Equity',
 'ZION UW Equity',
 'ZTS US Equity',
 'ZTS UN Equity',
 'D US Equity',
 'DAL US Equity',
 'DALRQ US Equity',
 'DCNAQ US Equity',
 'DD US Equity',
 'DDS US Equity',
 'DE US Equity',
 'DFODQ US Equity',
 'DFS US Equity',
 'DG US Equity',
 'DGX US Equity',
 'DHI US Equity',
 'DHR US Equity',
 'DIS US Equity',
 'DISCA UW Equity',
 'DISCK UW Equity',
 'DISH UW Equity',
 'DJ US Equity',
 'DLR US Equity',
 'DLTR UW Equity',
 'DLX US Equity',
 'DNRCQ US Equity',
 'DOC US Equity',
 'DOFSQ US Equity',
 'DOV US Equity',
 'DOW US Equity',
 'DPHIQ US Equity',
 'DRE US Equity',
 'DRI US Equity',
 'DTE US Equity',
 'DUK US Equity',
 'DVA US Equity',
 'DVN US Equity',
 'DVN UA Equity',
 'DXC US Equity',
 'DYNIQ US Equity',
 'EA UQ Equity',
 'EA UW Equity',
 'EBAY UQ Equity',
 'EBAY UW Equity',
 'ECL US Equity',
 'ED US Equity',
 'EFX US Equity',
 'EG US Equity',
 'EHC US Equity',
 'EIX US Equity',
 'EKDKQ US Equity',
 'EL US Equity',
 'ELV US Equity',
 'EMN US Equity',
 'EMR US Equity',
 'ENDPQ UW Equity',
 'ENRNQ US Equity',
 'EOG US Equity',
 'EOP US Equity',
 'EQIX UW Equity',
 'EQR US Equity',
 'EQT US Equity',
 'ES US Equity',
 'ESRX UQ Equity',
 'ESRX UW Equity',
 'ESS US Equity',
 'ETFC US Equity',
 'ETFC UW Equity',
 'ETN US Equity',
 'ETR US Equity',
 'EVHC US Equity',
 'EVRG US Equity',
 'EW US Equity',
 'EXC US Equity',
 'EXC UW Equity',
 'EXPD UW Equity',
 'EXPE UW Equity',
 'EXR US Equity',
 'F US Equity',
 'FANG UW Equity',
 'FAST UW Equity',
 'FBF US Equity',
 'FBIN US Equity',
 'FCX US Equity',
 'FDO US Equity',
 'FDX US Equity',
 'FE US Equity',
 'FFIV UW Equity',
 'FHI US Equity',
 'FHN US Equity',
 'FIS US Equity',
 'FISV UQ Equity',
 'FISV UW Equity',
 'FITB UQ Equity',
 'FITB UW Equity',
 'FJ US Equity',
 'FL US Equity',
 'FLIR UW Equity',
 'FLR US Equity',
 'FLS US Equity',
 'FLTWQ US Equity',
 'FMC US Equity',
 'FMCC US Equity',
 'FNMA US Equity',
 'FOSL UW Equity',
 'FOX UW Equity',
 'FOXA UW Equity',
 'FPC US Equity',
 'FRCB US Equity',
 'FRT US Equity',
 'FSH US Equity',
 'FSL/B US Equity',
 'FSLR UW Equity',
 'FTI US Equity',
 'FTLAQ US Equity',
 'FTNT UW Equity',
 'FTRCQ US Equity',
 'FTRCQ UW Equity',
 'FTV US Equity',
 'FWLT US Equity',
 'GAP US Equity',
 'GAPTQ US Equity',
 'GAS US Equity',
 'GBLXQ US Equity',
 'GD US Equity',
 'GDW US Equity',
 'GE US Equity',
 'GEN UQ Equity',
 'GEN UW Equity',
 'GENZ UQ Equity',
 'GENZ UW Equity',
 'GGP US Equity',
 'GHC US Equity',
 'GILD UQ Equity',
 'GILD UW Equity',
 'GIS US Equity',
 'GL US Equity',
 'GLW US Equity',
 'GM US Equity',
 'GMCR UW Equity',
 'GME US Equity',
 'GNW US Equity',
 'GOOG UW Equity',
 'GOOGL UQ Equity',
 'GOOGL UW Equity',
 'GPC US Equity',
 'GPN US Equity',
 'GPUI US Equity',
 'GR US Equity',
 'GRA US Equity',
 'GRMN UW Equity',
 'GS US Equity',
 'GT US Equity',
 'GT UW Equity',
 'GTW US Equity',
 'GWW US Equity',
 'HAL US Equity',
 'HAR US Equity',
 'HAS US Equity',
 'HAS US Equity.1',
 'HAS UW Equity',
 'HBAN UQ Equity',
 'HBAN UW Equity',
 'HBI US Equity',
 'HCA US Equity',
 'HCBK UW Equity',
 'HD US Equity',
 'HES US Equity',
 'HET US Equity',
 'HFC US Equity',
 'HIG US Equity',
 'HII US Equity',
 'HLT US Equity',
 'HM US Equity',
 'HNZ US Equity',
 'HOG US Equity',
 'HOLX UW Equity',
 'HON US Equity',
 'HOT US Equity',
 'HP US Equity',
 'HPC US Equity',
 'HPE US Equity',
 'HPQ US Equity',
 'HRB US Equity',
 'HRL US Equity',
 'HRZIQ US Equity',
 'HSH US Equity',
 'HSIC UW Equity',
 'HSP US Equity',
 'HST US Equity',
 'HSY US Equity',
 'HUM US Equity',
 'HWM US Equity',
 'IBM US Equity',
 'ICE US Equity',
 'IDXX UW Equity',
 'IEX US Equity',
 'IFF US Equity',
 'IKN US Equity',
 'ILMN UW Equity',
 'IMNX UQ Equity',
 'INCLF US Equity',
 'INCY UW Equity',
 'INTC UQ Equity',
 'INTC UW Equity',
 'INTU UQ Equity',
 'INTU UW Equity',
 'IP US Equity',
 'IPG US Equity',
 'IPGP UW Equity',
 'IQV US Equity',
 'IRM US Equity',
 'ISRG UW Equity',
 'IT US Equity',
 'ITT US Equity',
 'ITW US Equity',
 'IVZ US Equity',
 'JBHT UW Equity',
 'JBL US Equity',
 'JCI US Equity',
 'JEF US Equity',
 'JHF US Equity',
 'JKHY UW Equity',
 'JNJ US Equity',
 'JNPR US Equity',
 'JNPR UW Equity',
 'JNS US Equity',
 'JNY US Equity',
 'JOSEA US Equity',
 'JOY US Equity',
 'JOY UW Equity',
 'JPM US Equity',
 'JWN US Equity',
 'JWN UQ Equity',
 '0111145D US Equity',
 '0202445Q US Equity',
 '0203524D US Equity',
 '0226226D US Equity',
 '0544749D US Equity',
 '0574018D US Equity',
 '0772031D US Equity',
 '0820143D US Equity',
 '0848680D US Equity',
 '0867887D US Equity',
 '0872237D US Equity',
 '0910150D US Equity',
 '0948669D US Equity',
 '0961514D US Equity',
 '0964591D UQ Equity',
 '0964591D UW Equity',
 '1028411Q US Equity',
 '1040983D UQ Equity',
 '1051665D US Equity',
 '1086832D US Equity',
 '1255173D US Equity',
 '1255177D US Equity',
 '1255459D UW Equity',
 '1280712D UQ Equity',
 '1280712D UW Equity',
 '1281683D US Equity',
 '1284849D US Equity',
 '1288453D UW Equity',
 '1288652D US Equity',
 '1293405D US Equity',
 '1312089D US Equity',
 '1317355D US Equity',
 '140402Q US Equity',
 '1431816D US Equity',
 '1431816D UW Equity',
 '1436513D US Equity',
 '1448062D US Equity',
 '1448062D UW Equity',
 '1500785D US Equity',
 '1518855D US Equity',
 '1519128D UQ Equity',
 '1519128D UW Equity',
 '1520415D US Equity',
 '1524867D US Equity',
 '1528159D US Equity',
 '1539941D US Equity',
 '1541931D UQ Equity',
 '1541931D UW Equity',
 '1566019D US Equity',
 '1621582D US Equity',
 '1627457D US Equity',
 '1649858D US Equity',
 '1649858D UQ Equity',
 '1649858D UW Equity',
 '1654539D US Equity',
 '1683351D UQ Equity',
 '1683997D UQ Equity',
 '1683997D UW Equity',
 '1684442D US Equity',
 '1697067D US Equity',
 '1703561D US Equity',
 '1704453D US Equity',
 '1715651D US Equity',
 '1719868D US Equity',
 '1727044D US Equity',
 '1746513D UQ Equity',
 '1746513D UW Equity',
 '1752754D US Equity',
 '1778808D UQ Equity',
 '1789494D US Equity',
 '1799685D US Equity',
 '1806854D US Equity',
 '1810430D US Equity',
 '1812212D UW Equity',
 '1822785D US Equity',
 '1825471D US Equity',
 '1831877D US Equity',
 '183291Q US Equity',
 '1837572D US Equity',
 '1856613D US Equity',
 '1858968D US Equity',
 '1916672D US Equity',
 '1920486D UQ Equity',
 '1920486D UW Equity',
 '1922150D US Equity',
 '1927294D US Equity',
 '1972693D US Equity',
 '1996074D US Equity',
 '1996760D US Equity',
 '2071296D US Equity',
 '2073714D US Equity',
 '2078185D US Equity',
 '2207158D UQ Equity',
 '2207158D UW Equity',
 '2213185D US Equity',
 '2217347D UQ Equity',
 '222435Q US Equity',
 '2258717D US Equity',
 '2269312Q US Equity',
 '228510Q US Equity',
 '2288005Q US Equity',
 '2307532Q UQ Equity',
 '2307532Q UW Equity',
 '2326007D UQ Equity',
 '2326248D US Equity',
 '2326248D UW Equity',
 '236555Q US Equity',
 '2370058D US Equity',
 '244630Q UQ Equity',
 '2454227D US Equity',
 '2481644D US Equity',
 '2499073D US Equity',
 '2499073D UW Equity',
 '2502261D US Equity',
 '253647Q US Equity',
 '2544554D UW Equity',
 '2557974D US Equity',
 '2558202D US Equity',
 '2558202D UW Equity',
 '2567699D US Equity',
 '2572102D US Equity',
 '2572350D US Equity',
 '2584271D US Equity',
 '2596482D US Equity',
 '2596516D US Equity',
 '2613148D US Equity',
 '2616271D US Equity',
 '2619871D UQ Equity',
 '2619871D UW Equity',
 '2621018D US Equity',
 '2622092D US Equity',
 '2641504Q US Equity',
 '2676187Q UQ Equity',
 '2691Q US Equity',
 '2727195Q US Equity',
 '2731112Q US Equity',
 '2745Q US Equity',
 '2755Q US Equity',
 '2770014Q US Equity',
 '285939Q US Equity',
 '291784Q US Equity',
 '2942331Q US Equity',
 '2953349Q US Equity',
 '2968900Q US Equity',
 '2972Q US Equity',
 '297504Q US Equity',
 '2987536Q US Equity',
 '2999130Q US Equity',
 '300583Q US Equity',
 '301710Q US Equity',
 '3022239Q US Equity',
 '3026360Q US Equity',
 '3029830Q UQ Equity',
 '304024Q US Equity',
 '3054Q US Equity',
 '3075558Q US Equity',
 '3080867Q US Equity',
 '3133754Q US Equity',
 '3153670Q UQ Equity',
 '3179Q US Equity',
 '3253Q US Equity',
 '3277Q US Equity',
 '3286728Q US Equity',
 '329556Q US Equity',
 '3301Q US Equity',
 '3346Q US Equity',
 '3362726Q US Equity',
 '3393199Q US Equity',
 '3403545Q US Equity',
 '3414924Q US Equity',
 '3423152Q  US Equity',
 '3459Q US Equity',
 '3517233Q US Equity ',
 '3546Q US Equity',
 '355488Q US Equity',
 '355488Q UQ Equity',
 '3605818Q US Equity',
 '3621240Q US Equity',
 '363096Q US Equity',
 '3692470Q US Equity',
 '375573Q US Equity',
 '3891289Q US Equity',
 '390297Q US Equity',
 '399463Q US Equity',
 '41018Q US Equity',
 '45200Q US Equity',
 '4621824Q US Equity',
 '502466Q US Equity',
 '519239Q US Equity',
 '519239Q UQ Equity',
 '544791Q US Equity',
 '548227Q US Equity',
 '5656565D US Equity',
 '571300Q US Equity',
 '605018Q US Equity',
 '605555Q US Equity',
 '611647Q US Equity',
 '653707Q US Equity',
 '667517Q US Equity',
 '677004Q US Equity',
 '680884Q US Equity',
 '68335Q US Equity',
 '723588Q US Equity',
 '739306Q US Equity',
 '748957Q US Equity',
 '764144Q US Equity',
 '8206908Q UQ Equity',
 '8206908Q UW Equity',
 '8214761Q US Equity',
 '827663Q US Equity',
 '8277831Q US Equity',
 '8394653Q US Equity',
 '841273Q UQ Equity',
 '89236Q US Equity',
 '896661Q US Equity',
 '929530Q US Equity',
 '93916Q US Equity',
 '945852Q US Equity',
 '950967Q US Equity',
 '968734Q US Equity',
 '987200Q US Equity',
 '9876544D US Equity',
 '9876549D US Equity',
 '9876566D US Equity',
 '9903115D US Equity',
 '9980328D US Equity',
 '9983490D US Equity',
 '9990213D US Equity',
 '9990253D US Equity',
 '9991429D US Equity',
 'A US Equity',
 'AA US Equity',
 '9995522D US Equity',
 'AAPL UW Equity',
 'ABBV US Equity',
 'ABKFQ US Equity',
 'ABMD UW Equity',
 'ABT US Equity',
 'ACAS UW Equity',
 'ACKH US Equity',
 'ACN US Equity',
 'ADBE UQ Equity',
 'ADBE UW Equity',
 'ADI US Equity',
 'ADI UW Equity',
 'ADM US Equity',
 'ADP US Equity',
 'ADP UW Equity',
 'ADSK UQ Equity',
 'ADSK UW Equity',
 'AEE US Equity',
 'AEP US Equity',
 'AES US Equity',
 'AET US Equity',
 'AFL US Equity',
 'AFS US Equity',
 'AGN US Equity',
 'AIG US Equity',
 'AIV US Equity',
 'AIZ US Equity',
 'AJG US Equity',
 'AKAM UW Equity',
 'AKS US Equity',
 'ALB US Equity',
 'ALGN UW Equity',
 'ALK US Equity',
 'ALL US Equity',
 'ALLE US Equity',
 'ALXN UW Equity',
 'AMAT UQ Equity',
 'AMAT UW Equity',
 'AMCC UQ Equity',
 'AMCR US Equity',
 'AMD US Equity',
 'AMD UR Equity',
 'AMD UW Equity',
 'AME US Equity',
 'AMG US Equity',
 'AMGN UQ Equity',
 'AMGN UW Equity',
 'AMP US Equity',
 'AMT US Equity',
 'AMZN UQ Equity',
 'AMZN UW Equity',
 'AN US Equity',
 'ANDV US Equity',
 'ANDW UQ Equity',
 'ANDW UW Equity',
 'ANET US Equity',
 'ANF US Equity',
 'ANRZQ US Equity',
 'ANSS UW Equity',
 'AON US Equity',
 'AOS US Equity',
 'APA US Equity',
 'APD US Equity',
 'APH US Equity',
 'APOL UQ Equity',
 'APOL UW Equity',
 'ARE US Equity',
 'ARG US Equity',
 'ASH US Equity',
 'ATGE US Equity',
 'ATI US Equity',
 'ATO US Equity',
 ...]

In [16]:
#Calculating the 5 year rolling variance
rolling_var = returns_data[targets].rolling(window = 60).var()

In [26]:
beta_storage = {}

# Using for loop across all the equities and then calculating the rolling covariance and ultimately the betas with our factors
for equity in equities:
    equity_beta = pd.DataFrame(index=returns_data.index)

    for target in targets:
        # Calculate rolling covariance between the specific equity and target
        # This ensures we get a Series, not a DataFrame with multiple columns
        rolling_covariance = returns_data[equity].rolling(window=60).cov(returns_data[target])
        
        # Divide by the rolling variance of the target
        equity_beta[f'Beta_{target}'] = rolling_covariance / rolling_var[target]
        equity_beta.dropna(inplace = True)

    beta_storage[equity] = equity_beta

beta_storage

{'KATE US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        1.071011             0.981200                      1.437088
 2/27/2004        1.051220             0.973077                      1.400852
 3/31/2004        1.079137             0.985706                      1.422025
 4/30/2004        1.095161             1.048460                      1.468354
 5/31/2004        1.104481             1.056889                      1.473646
 ...                   ...                  ...                           ...
 8/30/2019        0.620214             0.698804                      1.098549
 9/30/2019        0.560739             0.634477                      1.023991
 10/31/2019       0.553807             0.628642                      1.017479
 11/29/2019       0.506752             0.597186                      0.920305
 12/31/2019       0.507241             0.596083                      0.922519

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 1/30/2004                -0.174195                           0.897176
 2/27/2004                -0.173824                           0.869878
 3/31/2004                -0.183136                           0.868981
 4/30/2004                -0.178265                           0.958247
 5/31/2004                -0.227571                           0.973323
 ...                            ...                                ...
 8/30/2019                 0.163025                           0.918462
 9/30/2019                 0.239905                           0.862553
 10/31/2019                0.259163                           0.856121
 11/29/2019                0.213240                           0.796731
 12/31/2019                0.212599                           0.800007

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 1/30/2004                1.115415                0.857094
 2/27/2004                1.088006                0.835372
 3/31/2004                1.114842                0.873733
 4/30/2004                1.105525                0.880569
 5/31/2004                1.121941                0.892549
 ...                           ...                     ...
 8/30/2019                0.578807                0.423694
 9/30/2019                0.528634                0.371637
 10/31/2019               0.519696                0.365868
 11/29/2019               0.483820                0.297042
 12/31/2019               0.483721                0.301023

 [192 rows x 7 columns],
 'KBH US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        0.569813             0.558948                      0.899487
 2/27/2004        0.533720             0.549162                      0.836843
 3/31/2004        0.535660             0.544108                      0.840738
 4/30/2004        0.543410             0.562933                      0.861898
 5/31/2004        0.533313             0.556622                      0.851579
 ...                   ...                  ...                           ...
 8/30/2019        1.338209             1.355036                      1.628060
 9/30/2019        1.312975             1.375526                      1.554516
 10/31/2019       1.312318             1.374432                      1.551259
 11/29/2019       1.259826             1.333895                      1.509465
 12/31/2019       1.235663             1.309971                      1.487423

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 1/30/2004                 0.091748                           0.654657
 2/27/2004                 0.094287                           0.606103
 3/31/2004                 0.097260                           0.587380
 4/30/2004                 0.103289                           0.604012
 5/31/2004                 0.138902                           0.600127
 ...                            ...                                ...
 8/30/2019                -0.119732                           1.304140
 9/30/2019                -0.143580                           1.343922
 10/31/2019               -0.122380                           1.339052
 11/29/2019               -0.151738                           1.299429
 12/31/2019               -0.144738                           1.272198

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 1/30/2004                0.633788                0.746141
 2/27/2004                0.580787                0.708423
 3/31/2004                0.580344                0.726339
 4/30/2004                0.553307                0.771837
 5/31/2004                0.549143                0.757319
 ...                           ...                     ...
 8/30/2019                1.223284                1.290992
 9/30/2019                1.188004                1.170510
 10/31/2019               1.186795                1.163597
 11/29/2019               1.134411                1.112975
 12/31/2019               1.104611                1.093723

 [192 rows x 7 columns],
 'KDP US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 4/30/2013        0.704531             0.730930                      1.070362
 5/31/2013        0.704300             0.716856                      1.084999
 6/28/2013        0.641804             0.653220                      1.009497
 7/31/2013        0.632103             0.646195                      1.006383
 8/30/2013        0.633388             0.646180                      0.995827
 ...                   ...                  ...                           ...
 8/30/2019        0.121164            -0.017469                      0.314896
 9/30/2019        0.129372            -0.010201                      0.326888
 10/31/2019       0.118540            -0.021864                      0.263677
 11/29/2019       0.140416             0.001511                      0.233465
 12/31/2019       0.116333            -0.022461                      0.212125

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 4/30/2013                 0.387160                           0.876389
 5/31/2013                 0.410559                           0.866911
 6/28/2013                 0.429170                           0.798846
 7/31/2013                 0.434117                           0.799897
 8/30/2013                 0.439193                           0.795159
 ...                            ...                                ...
 8/30/2019                -0.343844                           0.030364
 9/30/2019                -0.350983                           0.035676
 10/31/2019               -0.314451                           0.013633
 11/29/2019               -0.327222                           0.011766
 12/31/2019               -0.341893                          -0.014729

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 4/30/2013                0.734494                0.562811
 5/31/2013                0.739972                0.592299
 6/28/2013                0.663218                0.575887
 7/31/2013                0.654365                0.578586
 8/30/2013                0.645347                0.602288
 ...                           ...                     ...
 8/30/2019                0.154497                0.352461
 9/30/2019                0.161495                0.356562
 10/31/2019               0.150424                0.341481
 11/29/2019               0.180491                0.348188
 12/31/2019               0.150973                0.334179

 [81 rows x 7 columns],
 'KEY US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        0.221631             0.656451                      0.865502
 2/27/2004        0.227428             0.660489                      0.882529
 3/31/2004        0.255717             0.679480                      0.907627
 4/30/2004        0.255517             0.707021                      0.922173
 5/31/2004        0.280121             0.726020                      0.943228
 ...                   ...                  ...                           ...
 8/30/2019        1.285254             1.462197                      0.806690
 9/30/2019        1.293746             1.475015                      0.797767
 10/31/2019       1.298663             1.480943                      0.830123
 11/29/2019       1.314072             1.493886                      0.838929
 12/31/2019       1.323026             1.499198                      0.851304

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 1/30/2004                 0.440275                           1.088887
 2/27/2004                 0.443772                           1.101803
 3/31/2004                 0.431325                           1.107323
 4/30/2004                 0.431569                           1.194856
 5/31/2004                 0.372030                           1.219990
 ...                            ...                                ...
 8/30/2019                 0.006998                           1.148523
 9/30/2019                -0.015401                           1.163587
 10/31/2019               -0.023597                           1.173667
 11/29/2019               -0.022800                           1.188815
 12/31/2019               -0.014169                           1.205054

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 1/30/2004                0.046451               -0.100792
 2/27/2004                0.054216               -0.096795
 3/31/2004                0.082073               -0.069694
 4/30/2004                0.077739               -0.061160
 5/31/2004                0.100299               -0.026577
 ...                           ...                     ...
 8/30/2019                1.078946                0.810350
 9/30/2019                1.079977                0.775849
 10/31/2019               1.083454                0.780155
 11/29/2019               1.098985                0.799891
 12/31/2019               1.108887                0.815453

 [192 rows x 7 columns],
 'KEYS US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 10/31/2019       1.295569             1.154416                      1.381394
 11/29/2019       1.278648             1.145672                      1.346289
 12/31/2019       1.245953             1.112448                      1.318595

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 10/31/2019               -0.609663                           1.190617
 11/29/2019               -0.634780                           1.170829
 12/31/2019               -0.640323                           1.136864

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 10/31/2019               1.306556                1.210419
 11/29/2019               1.291560                1.189680
 12/31/2019               1.250341                1.171486  ,
 'KHC UW Equity': Empty DataFrame
 Columns: [Beta_MSCI USA, Beta_MSCI USA Value, Beta_MSCI USA Low Volatility, Beta_MSCI USA Low Size, Beta_MSCI USA High Dividend Yield, Beta_MSCI USA Quality, Beta_MSCI USA Momentum]
 Index: [],
 'KIM US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        0.119323             0.205507                      0.204589
 2/27/2004        0.112274             0.203285                      0.192239
 3/31/2004        0.115523             0.201471                      0.197476
 4/30/2004        0.120048             0.202671                      0.204545
 5/31/2004        0.127994             0.207538                      0.212418
 ...                   ...                  ...                           ...
 8/30/2019        0.603741             0.646026                      1.256627
 9/30/2019        0.602393             0.679833                      1.230501
 10/31/2019       0.578976             0.657328                      1.137162
 11/29/2019       0.571192             0.651193                      1.141404
 12/31/2019       0.555842             0.633552                      1.129979

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 1/30/2004                 0.046025                           0.208968
 2/27/2004                 0.046199                           0.200017
 3/31/2004                 0.046005                           0.185060
 4/30/2004                 0.052048                           0.164586
 5/31/2004                 0.039475                           0.167063
 ...                            ...                                ...
 8/30/2019                -0.482705                           0.766632
 9/30/2019                -0.519985                           0.809758
 10/31/2019               -0.457509                           0.773582
 11/29/2019               -0.464875                           0.770225
 12/31/2019               -0.474126                           0.756607

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 1/30/2004                0.043557                0.040528
 2/27/2004                0.032457                0.032638
 3/31/2004                0.033393                0.042640
 4/30/2004                0.006961                0.099309
 5/31/2004                0.009419                0.111600
 ...                           ...                     ...
 8/30/2019                0.582634                0.563462
 9/30/2019                0.571991                0.495021
 10/31/2019               0.545610                0.469331
 11/29/2019               0.536950                0.463830
 12/31/2019               0.517615                0.459582

 [192 rows x 7 columns],
 'KLAC UQ Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        2.494912             1.789227                      2.190980
 2/27/2004        2.472370             1.768093                      2.132671
 3/31/2004        2.532637             1.794562                      2.171416
 4/30/2004        2.574395             1.919114                      2.261622
 5/31/2004        2.575218             1.915806                      2.262110
 ...                   ...                  ...                           ...
 8/30/2019        1.609574             1.647509                      1.716982
 9/30/2019        1.634753             1.671638                      1.735121
 10/31/2019       1.646775             1.681708                      1.770038
 11/29/2019       1.649736             1.676669                      1.877427
 12/31/2019       1.662317             1.688252                      1.891331

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 1/30/2004                -0.603024                           0.577890
 2/27/2004                -0.614480                           0.538664
 3/31/2004                -0.634446                           0.545715
 4/30/2004                -0.619968                           0.615911
 5/31/2004                -0.608102                           0.599890
 ...                            ...                                ...
 8/30/2019                -0.664814                           1.862744
 9/30/2019                -0.699216                           1.879227
 10/31/2019               -0.702772                           1.889667
 11/29/2019               -0.673305                           1.934752
 12/31/2019               -0.642227                           1.952826

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 1/30/2004                2.593235                2.443130
 2/27/2004                2.565015                2.421722
 3/31/2004                2.623131                2.512476
 4/30/2004                2.593607                2.539815
 5/31/2004                2.586187                2.543877
 ...                           ...                     ...
 8/30/2019                1.697436                1.442915
 9/30/2019                1.714409                1.419212
 10/31/2019               1.727899                1.419769
 11/29/2019               1.709313                1.462244
 12/31/2019               1.722000                1.476570

 [192 rows x 7 columns],
 'KLAC UW Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        2.494912             1.789227                      2.190980
 2/27/2004        2.472370             1.768093                      2.132671
 3/31/2004        2.532637             1.794562                      2.171416
 4/30/2004        2.574395             1.919114                      2.261622
 5/31/2004        2.575218             1.915806                      2.262110
 ...                   ...                  ...                           ...
 8/30/2019        1.609574             1.647509                      1.716982
 9/30/2019        1.634753             1.671638                      1.735121
 10/31/2019       1.646775             1.681708                      1.770038
 11/29/2019       1.649736             1.676669                      1.877427
 12/31/2019       1.662317             1.688252                      1.891331

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \
 1/30/2004                -0.603024                           0.577890
 2/27/2004                -0.614480                           0.538664
 3/31/2004                -0.634446                           0.545715
 4/30/2004                -0.619968                           0.615911
 5/31/2004                -0.608102                           0.599890
 ...                            ...                                ...
 8/30/2019                -0.664814                           1.862744
 9/30/2019                -0.699216                           1.879227
 10/31/2019               -0.702772                           1.889667
 11/29/2019               -0.673305                           1.934752
 12/31/2019               -0.642227                           1.952826

             Beta_MSCI USA Quality  Beta_MSCI USA Momentum
 1/30/2004                2.593235                2.443130
 2/27/2004                2.565015                2.421722
 3/31/2004                2.623131                2.512476
 4/30/2004                2.593607                2.539815
 5/31/2004                2.586187                2.543877
 ...                           ...                     ...
 8/30/2019                1.697436                1.442915
 9/30/2019                1.714409                1.419212
 10/31/2019               1.727899                1.419769
 11/29/2019               1.709313                1.462244
 12/31/2019               1.722000                1.476570

 [192 rows x 7 columns],
 'KMB US Equity':             Beta_MSCI USA  Beta_MSCI USA Value  Beta_MSCI USA Low Volatility  \
 1/30/2004        0.278249             0.565779                      0.906662
 2/27/2004        0.275563             0.570755                      0.911705
 3/31/2004        0.279931             0.574283                      0.916407
 4/30/2004        0.208628             0.428811                      0.773244
 5/31/2004        0.201894             0.423769                      0.767830
 ...                   ...                  ...                           ...
 8/30/2019        0.545284             0.588226                      1.126986
 9/30/2019        0.545708             0.581861                      1.131564
 10/31/2019       0.521210             0.563733                      1.132289
 11/29/2019       0.511638             0.558379                      1.113528
 12/31/2019       0.509071             0.555374                      1.111860

             Beta_MSCI USA Low Size  Beta_MSCI USA High Dividend Yield  \

In [28]:
beta_df = pd.concat(beta_storage, axis=1)
beta_df.columns = ['_'.join(col).strip() for col in beta_df.columns.values]
beta_df.head()

,KATE US Equity_Beta_MSCI USA,KATE US Equity_Beta_MSCI USA Value,KATE US Equity_Beta_MSCI USA Low Volatility,KATE US Equity_Beta_MSCI USA Low Size,KATE US Equity_Beta_MSCI USA High Dividend Yield,KATE US Equity_Beta_MSCI USA Quality,KATE US Equity_Beta_MSCI USA Momentum,KBH US Equity_Beta_MSCI USA,KBH US Equity_Beta_MSCI USA Value,KBH US Equity_Beta_MSCI USA Low Volatility,...,CVX US Equity_Beta_MSCI USA High Dividend Yield,CVX US Equity_Beta_MSCI USA Quality,CVX US Equity_Beta_MSCI USA Momentum,CXO US Equity_Beta_MSCI USA,CXO US Equity_Beta_MSCI USA Value,CXO US Equity_Beta_MSCI USA Low Volatility,CXO US Equity_Beta_MSCI USA Low Size,CXO US Equity_Beta_MSCI USA High Dividend Yield,CXO US Equity_Beta_MSCI USA Quality,CXO US Equity_Beta_MSCI USA Momentum
1/30/2004,1.071011,0.981200,1.437088,-0.174195,0.897176,1.115415,0.857094,0.569813,0.558948,0.899487,...,0.963413,0.561943,0.498918,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2/27/2004,1.051220,0.973077,1.400852,-0.173824,0.869878,1.088006,0.835372,0.533720,0.549162,0.836843,...,0.978421,0.577005,0.508212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3/31/2004,1.079137,0.985706,1.422025,-0.183136,0.868981,1.114842,0.873733,0.535660,0.544108,0.840738,...,0.983925,0.539222,0.459999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4/30/2004,1.095161,1.048460,1.468354,-0.178265,0.958247,1.105525,0.880569,0.543410,0.562933,0.861898,...,0.956123,0.534892,0.438726,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5/31/2004,1.104481,1.056889,1.473646,-0.227571,0.973323,1.121941,0.892549,0.533313,0.556622,0.851579,...,0.946259,0.523770,0.422173,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
beta_df.tail()

,KATE US Equity_Beta_MSCI USA,KATE US Equity_Beta_MSCI USA Value,KATE US Equity_Beta_MSCI USA Low Volatility,KATE US Equity_Beta_MSCI USA Low Size,KATE US Equity_Beta_MSCI USA High Dividend Yield,KATE US Equity_Beta_MSCI USA Quality,KATE US Equity_Beta_MSCI USA Momentum,KBH US Equity_Beta_MSCI USA,KBH US Equity_Beta_MSCI USA Value,KBH US Equity_Beta_MSCI USA Low Volatility,...,CVX US Equity_Beta_MSCI USA High Dividend Yield,CVX US Equity_Beta_MSCI USA Quality,CVX US Equity_Beta_MSCI USA Momentum,CXO US Equity_Beta_MSCI USA,CXO US Equity_Beta_MSCI USA Value,CXO US Equity_Beta_MSCI USA Low Volatility,CXO US Equity_Beta_MSCI USA Low Size,CXO US Equity_Beta_MSCI USA High Dividend Yield,CXO US Equity_Beta_MSCI USA Quality,CXO US Equity_Beta_MSCI USA Momentum
8/30/2019,0.620214,0.698804,1.098549,0.163025,0.918462,0.578807,0.423694,1.338209,1.355036,1.628060,...,1.259105,0.841425,0.681201,1.247245,1.451999,0.874155,-0.406488,1.273638,1.067427,0.807125
9/30/2019,0.560739,0.634477,1.023991,0.239905,0.862553,0.528634,0.371637,1.312975,1.375526,1.554516,...,1.229196,0.823831,0.655237,1.209468,1.378797,0.834541,-0.323584,1.199061,1.039112,0.797914
10/31/2019,0.553807,0.628642,1.017479,0.259163,0.856121,0.519696,0.365868,1.312318,1.374432,1.551259,...,1.233927,0.816301,0.657378,1.237579,1.405865,0.954863,-0.383602,1.239796,1.069610,0.820908
11/29/2019,0.506752,0.597186,0.920305,0.213240,0.796731,0.483820,0.297042,1.259826,1.333895,1.509465,...,1.272682,0.825206,0.697796,1.289370,1.443054,1.050432,-0.348487,1.304341,1.111425,0.896227
12/31/2019,0.507241,0.596083,0.922519,0.212599,0.800007,0.483721,0.301023,1.235663,1.309971,1.487423,...,1.288812,0.835151,0.714276,1.350603,1.504887,1.106159,-0.280530,1.373721,1.184894,0.936456